# Site settings
title: Hellen & Michas Rezeptsammlung ğŸ¥•ğŸ¥”ğŸ†
email: 
description: The plain text recipe database for hackers
baseurl: "https://hellenundmicha.github.io/Rezeptsammlung/"
language: "en"
lang_direction: "ltr"
color: "#007FFF"
twitter_username: 
github_username:

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'templates']
